"""
Doubled im Python C enum which is used for communicating the change of window state
"""
from enum import IntFlag

class WindowSignal(IntFlag):
	WINDOW_SIGNAL_CLOSED = 1
	WINDOW_SIGNAL_RESIZED = 2
	WINDOW_SIGNAL_SHOWN = 4
	WINDOW_SIGNAL_HIDDEN = 8
	WINDOW_SIGNAL_EXPOSED = 16
	WINDOW_SIGNAL_MOVED = 32
	WINDOW_SIGNAL_MINIMIZED = 64
	WINDOW_SIGNAL_MAXIMIZED = 128
	WINDOW_SIGNAL_RESTORED = 256
	WINDOW_SIGNAL_MOUSE_ENTERED = 512
	WINDOW_SIGNAL_MOUSE_EXITED = 1024
	WINDOW_SIGNAL_FOCUS_GAINED = 2048
	WINDOW_SIGNAL_FOCUS_LOST = 4096
